FROM php:7.4-fpm

RUN apt-get update
RUN apt-get install -y autoconf pkg-config libssl-dev libzip-dev git curl zip unzip zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev

# Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# MySQL
RUN docker-php-ext-install pdo pdo_mysql mysqli zip

# Install PhpRedis extension
RUN pecl install redis && docker-php-ext-enable redis